trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
      - 'doc-site/'

pr:
  branches:
    include:
    - '*'
  paths:
    include:
      - 'doc-site/'

pool:
  vmImage: 'ubuntu-latest'
  
stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseRubyVersion@0
            inputs:
              versionSpec: '~> 3.1' 
     
          - powershell: ./build-scripts/build.ps1
            workingDirectory: doc-site
            displayName: "Build"
        
          - powershell: ./build-scripts/push.ps1 -githubtoken $(githubtoken)
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
            workingDirectory: doc-site
            displayName: "Deploy"
          
  